### ISSUE TITLE
R_omp_max bug fix only applies when using Gaussian Spreading

### ISSUE THREAD

**Issue by shawnzamperini** [plasmapotential/HEAT#11]
Recent [bug fix](https://github.com/plasmapotential/HEAT/commit/3e68a0a1ee23a240b9dbd88033fe7f553f041657) only applies when using Gaussian Spreading heat flux profile. Testing with Multi-Exponential with large width bypasses the fix in heatFlux.scaleHF_fluxspace.

**Comment by plasmapotential** [comment]
Ahh yes sorry for only part of the job.  

added check to prevent R_omp_max from going outside the EFIT grid in both heatFlux.findScalingCoeffsMultiExp() and heatFlux.findScalingCoeffsLimiter()

https://github.com/plasmapotential/HEAT/blob/cf4535c4844d8c2def5a7fac10679134204f40b0/source/heatfluxClass.py#L437
