### ISSUE TITLE
It's not a issue, a suggestion

### ISSUE THREAD

**Issue by msubraman** [plasmapotential/HEAT#13]
Hi Tom,

Is it possible for you add/change the visualization of the results (colouring), i.e, colouring the element instead of the integration points or give flexibility for user to choose both (colouring in element and integration points).

Thanks 
Manoj

**Comment by plasmapotential** [comment]
Thanks for the note, Manoj.  

This is something I have had a few users request, so I intend on adding it to the code.  It is, however, very low on the priority list compared to some of my other items (radiated power, acceleration structures, etc.) so it may be a bit of time before it is implemented.  I will try to add to the next release (but not making any promises).  Thanks for the feedback this is very useful.

-tom

**Comment by plasmapotential** [comment]
I will leave this issue open until it is added to the code

**Comment by msubraman** [comment]
Ok, Thanks Tom.
