### ISSUE TITLE
New version of heat not working properly

### ISSUE THREAD

**Issue by msubraman** [plasmapotential/HEAT#14]
Hi Tom,

Manoj from UKAEA.
I followed the steps for the installation of HEAT with docker (v3). Everything went well but the GUI is not working well. 
GUI looks different (picture attached) as well as giving errors while loading the files (input, eqdsk,..) 
I have also included docker-compose.yml and runDockerCompose

![1 1](https://user-images.githubusercontent.com/77074349/200882152-ae77ea6c-114b-489b-aab6-0d2d9fd56333.PNG)
![1 2](https://user-images.githubusercontent.com/77074349/200882156-93e991d8-f945-4949-9003-d96e4fae4437.PNG)
![1 3](https://user-images.githubusercontent.com/77074349/200882158-9eb08814-e35e-48cb-801d-2c09313c64a0.PNG)
![docker-compose yml](https://user-images.githubusercontent.com/77074349/200882161-530a41f1-e498-48de-a871-a401ac8071e7.PNG)
![runDockerCompose](https://user-images.githubusercontent.com/77074349/200882165-6e1f19d7-3ce5-482f-a67b-63223e92fa7e.PNG)

**Comment by plasmapotential** [comment]
Hey Manoj,

Thanks for submitting this issue.

I think you are missing the radiated power settings in your input file.  The Radiated power section of the input file should look like this

```
   #==============================================================
   #                Radiated Power HF Variables
   #==============================================================
   radFile, /home/tom/HEATruns/testCase_v3.0.0/nstx/RZpower.csv
   Ntor, 5
   Nref, 1
   phiMin, 20
   phiMax, 35

```

Could you upload the NSTXU_input.csv file that you are using?  Is this the NSTXU_input.csv file that came from the HEAT releases tab (testCase_v3.0.zip) ?  https://github.com/plasmapotential/HEAT/releases/tag/v3.0

**Comment by plasmapotential** [comment]
One more comment.  The GUI theme can now be changed in HEAT in the top right corner using the "Change Theme" button

**Comment by msubraman** [comment]
The problem still exist after trying both ways as mentioned above.
But I found a solution using 'export HOME=/mnt/...' , that's working and I can open the results.

My results gyro results are not showing any heat flux mapping, so I think it's lack of knowledge for me to use the gyro parameters. To understand better the testcase for gyro/photon and new features, I think we can meet and you can guide me through. I will send you an email.

**Comment by plasmapotential** [comment]
ok I think in a meeting we will clear this up.  One other thing you could try is to install the latest version of docker.

I have been meaning to update all the youtube tutorials and to include a youtube video for both gyro orbit and radiated power, but I cannot seem to find the time to do this.  Hopefully over the holidays things will slow down and I will be able to publish these tutorials.  But yes, let's meet and I will describe everything.

I will wait to close this thread until we find a solution in our meeting.  I will post the solution here for future users.

**Comment by plasmapotential** [comment]
solved by using runDockerCompose and uncommenting the "environment" section of the recipe YAML file, docker-compose.yml
