### ISSUE TITLE
How can I get animation as showed in README?

### ISSUE THREAD

**Issue by yuriydev214** [plasmapotential/HEAT#2]
Hi, I am interested in your project and I tried to get the animation in my Ubuntu system. In fact I am going to get a program which shows simulation of divertor.
But I am not sure how I can get animation as you showed in README file.
I have also installed ParaView in Ubuntu.
Could you teach me with below two questions?
1. How I can get animation,
2. Can I build the project in Windows?
Thanks, Yuriy.

**Comment by plasmapotential** [comment]
Hey Yuriy,

To get the animations shown in the GUI, you need to 
1) download the HEAT appImage, 
2) run the HEAT test case, and then 
3) in ParaView open all the .vtk files that HEAT creates when it runs.
4)  After you import the HEAT results into ParaView, then you can save into a video by clicking File > Save Animation.

To help you with steps 1) - 3), there is a readthedocs wiki page with some tutorial videos here: 
(https://heat-flux-engineering-analysis-toolkit-heat.readthedocs.io/en/latest/)

And no, this project cannot be run on windows.  AppImages are Linux only files, and many of the dependencies included in HEAT submodules are linux only.  You Ubuntu installation should be perfect, though!

Feel free to email me with any questions.  tlooby@vols.utk.edu
-tom
