### ISSUE TITLE
plasma3Dbranch variables not initialized, but required in engineClass

### ISSUE THREAD

**Issue by tloobyCFS** [plasmapotential/HEAT#26]
when running a batch mode calculation, the input variables for the plasma3D class and hf3D are not initialized from the input file (when NOT running plasma3D).  This would be fine except for the fact that other classes and functions require plasma3Dmask to be set.  

This should happen in engineClass.loadInputs(): https://github.com/plasmapotential/HEAT/blob/f6b7d74b10e56f0bb458f2bc4cec990e80a039df/source/engineClass.py#L3375

These lines should be added:

```
tools.initializeInput(self.plasma3D, self.infile)   
tools.initializeInput(self.hf3D, self.infile)   
```

and the inputDict should be updated to contain the parameters from both plasma3D and hf3D.

additionally, the functions `engineClass.getCurrentInputs()`, `engineClass.getDefaultDict()`, and `toolsClass.saveInputFile()` should be updated with plasma3D and hf3D, so that input dictionaries and input file saves contain the new plasma3D variables

finally, the input files in the nstxu test cases should be updated with the required variables for both 3d field classes:  
https://github.com/plasmapotential/HEAT/blob/f6b7d74b10e56f0bb458f2bc4cec990e80a039df/tests/integrationTests/nstxuTestCase/nstx/NSTXU_input.csv

to replicate the error behavior, run a HEAT batch mode simulation with only psiN turned on in the batchFile.  the traceback looks like this:

```
Traceback (most recent call last):
  File "/root/source/HEAT/source/launchHEAT.py", line 319, in <module>
    launchHEAT(args)
  File "/root/source/HEAT/source/launchHEAT.py", line 262, in launchHEAT
    tui.runSimulations()
  File "/root/source/HEAT/source/terminalUI.py", line 282, in runSimulations
    self.runHEAT(inputFiles, runList)
  File "/root/source/HEAT/source/terminalUI.py", line 301, in runHEAT
    self.ENG.runHEAT(runList)
  File "/root/source/HEAT/source/engineClass.py", line 1836, in runHEAT
    self.psiPC(PFC)
  File "/root/source/HEAT/source/engineClass.py", line 3262, in psiPC
    self.getPsiEverywhere(PFC, PFC.tag)
  File "/root/source/HEAT/source/engineClass.py", line 3274, in getPsiEverywhere
    if self.plasma3D.plasma3Dmask:
AttributeError: 'plasma3D' object has no attribute 'plasma3Dmask'
```

**Comment by wingena** [comment]
This is now comprehensively fixed in the plasma3D branch, inlcuding the engineCalss and toolClass functions as well as the NSTX test case input file
This issue is now closed!
