### ISSUE TITLE
foam file missing fields when deltaT != write deltaT

### ISSUE THREAD

**Issue by chrismarsden7** [plasmapotential/HEAT#4]
Example:

When running openFOAM over 10,000ms, I have selected deltaT = 0.01 and write deltaT to 0.1. When this happens, the temp (and heat flux) fields are output every 0.1s, with the interpolated heat flux (only) also output every 0.01s. It then seems as if heat is unable to create a foam file containing the temperature when this is the case. When deltaT and write deltaT as exactly equal, you do not get these intermediary folders created (the ones containing only the heat flux), and heat is able to create the temperature field in the foam file.

I suspect heat looks for fields which are common amongst all the folders, including in those that didn't actually have new data (T etc) in them (only containing the extrapolated heat flux), and hence as heat flux is the only common field amongst all folders, that is the only one that survives to the output foam file.

**Comment by plasmapotential** [comment]
user can no longer edit writeDeltaT in v3.0
